# /// script
# requires-python = ">=3.11"
# ///
"""Storyboard → composer props. The invariant enforcer.

Usage:
  video-studio build_props --storyboard project/storyboard.json \
      --project project/ --composer composer/ [--placeholders]

What it enforces (never trust upstream to have done it):
- THE CLOCK: a scene with narration audio gets durationInFrames from the
  MEASURED WAV duration (ffprobe), never from plannedSeconds. Silent scenes
  fall back to plannedSeconds, then to longest layer media, then 4s.
- Captions come from the scene's .timings.json (scene-relative ms — the
  composer's <Sequence> makes that the right frame of reference).
- Media referenced by props must live under composer/public/ — this script
  copies project assets in and rewrites sources to public-relative paths.
- With --placeholders, any unresolved source (prompt:/find:/url:) renders as
  a labeled shape so layout/timing preview costs nothing. Without it,
  unresolved sources are a hard error listing exactly what's missing.

Project dir conventions:
  project/storyboard.json
  project/audio/<sceneId>.wav + <sceneId>.timings.json   (from tts_kokoro.py)
  project/clips/<sceneId>-<layerId>.(mp4|webm|png|jpg)   (resolved footage)

Prints JSON summary: scenes, total seconds, unresolved count.
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from pathlib import Path
from video_studio.paths import studio_root

#: Card keys the composer actually renders. Anything else is dropped silently.
CARD_KEYS = {"heading", "subtext", "lines", "bg", "fg", "size", "tracking",
             "footnote", "align", "fontSize", "flat"}
LAYER_KEYS = ("rect", "enter", "exit", "fit", "atMs", "untilMs", "pop", "ken", "fade")
EFFECT_KEYS = ("effect", "intensity", "palette")

PLACEHOLDER_COLORS = ["#3b5b7a", "#7a3b5b", "#3b7a5b", "#7a6a3b", "#5b3b7a"]
IMAGE_EXTS = {".png", ".jpg", ".jpeg", ".webp"}


def write_registry(composer: Path) -> None:
    """Regenerate the composition registry from whatever props files exist.

    One Composition per project is what makes concurrent work safe: agents pick
    their own composition instead of contending for a single global document.
    The previous design had Root.tsx statically import one props.json, so
    whoever wrote that file last defined what EVERY open editor displayed.

    Generated rather than hand-maintained, and derived purely from the directory
    listing, so two agents building at once produce byte-identical output.
    """
    props_dir = composer / "props"
    props_dir.mkdir(parents=True, exist_ok=True)
    src_dir = composer / "src"
    src_dir.mkdir(parents=True, exist_ok=True)
    slugs = sorted(p.stem for p in props_dir.glob("*.json"))
    lines = [
        "// GENERATED by scripts/build_props.py — do not edit.",
        "// One entry per project; each is its own composition in the editor.",
        'import type { VideoProps } from "./Video";',
        "",
    ]
    for i, slug in enumerate(slugs):
        lines.append(f'import p{i} from "../props/{slug}.json";')
    lines.append("")
    lines.append("export const PROJECTS: Record<string, VideoProps> = {")
    for i, slug in enumerate(slugs):
        lines.append(f'  {json.dumps(slug)}: p{i} as unknown as VideoProps,')
    lines.append("};")
    (src_dir / "registry.ts").write_text("\n".join(lines) + "\n")


def media_seconds(path: Path) -> float:
    result = subprocess.run(
        ["ffprobe", "-v", "error", "-show_entries", "format=duration",
         "-of", "default=noprint_wrappers=1:nokey=1", str(path)],
        capture_output=True, text=True,
    )
    if result.returncode != 0:
        raise RuntimeError(f"ffprobe failed for {path}: {result.stderr.strip()[:200]}")
    return float(result.stdout.strip())


def parse_source(source: str) -> tuple[str, str]:
    """-> (kind, value) where kind in prompt|file|url|find|placeholder."""
    for kind in ("prompt", "file", "url", "find", "placeholder"):
        prefix = f"{kind}:"
        if source.startswith(prefix):
            return kind, source[len(prefix):].strip()
    raise ValueError(f"layer source must start with prompt:/file:/url:/find:/placeholder: — got {source!r}")


def slugify(project: Path) -> str:
    """Stable id for a project: its directory name."""
    return project.resolve().name


def build(storyboard_path: Path, project: Path, composer: Path, placeholders: bool) -> dict:
    sb = json.loads(storyboard_path.read_text())
    fps = int(sb.get("fps", 30))
    slug = slugify(project)
    # Media lives under public/<project>/, never a shared flat directory.
    # It used to be public/clips/<sceneId>-<layerId>.mp4 for EVERY project at
    # once: two projects with a scene called "hook" and a layer called "still"
    # silently overwrote each other, and whichever built last won — including
    # for a render already in progress.
    public = composer / "public" / slug
    (public / "audio").mkdir(parents=True, exist_ok=True)
    (public / "clips").mkdir(parents=True, exist_ok=True)

    unresolved: list[str] = []
    # Placeholdered layers are NOT the same as unresolved ones, and conflating
    # them is how a render ships as solid colored boxes: with --placeholders on,
    # every missing asset silently became a placeholder while the summary still
    # read {"unresolved": 0}, which reads as success. Counted separately so the
    # summary can never again report a placeholder-only build as resolved.
    placeholdered: list[str] = []
    scenes = []
    # Frame-snap cumulative boundaries, not each duration on its own. Rounding
    # every scene independently lets error accumulate down the timeline: a
    # 7-scene edit drifted its 5th cut 158ms early and put narration 218ms
    # behind the picture. Snapping the running total keeps every cut on the
    # nearest frame to its true time.
    cum_seconds = 0.0
    prev_frame = 0
    for si, scene in enumerate(sb["scenes"]):
        sid = scene["id"]

        # --- the clock ---
        wav = project / "audio" / f"{sid}.wav"
        audio_rel = None
        if wav.exists():
            seconds = media_seconds(wav)
            shutil.copy2(wav, public / "audio" / wav.name)
            audio_rel = f"{slug}/audio/{wav.name}"
        elif scene.get("plannedSeconds"):
            seconds = float(scene["plannedSeconds"])
        else:
            layer_files = [
                project / "clips" / f"{sid}-{layer['id']}{ext}"
                for layer in scene["layers"]
                for ext in (".mp4", ".webm")
            ]
            found = [media_seconds(f) for f in layer_files if f.exists()]
            seconds = max(found) if found else 4.0

        # --- captions (scene-relative ms; Sequence gives local frames) ---
        captions = None
        timings = project / "audio" / f"{sid}.timings.json"
        if timings.exists():
            captions = json.loads(timings.read_text())

        # --- layers ---
        layers = []
        for li, layer in enumerate(scene["layers"]):
            # Effects resolve no file and carry no typography, so they are
            # settled first — before the card guard below, which would
            # otherwise have to reason about a layer kind it knows nothing of.
            if "effect" in layer:
                entry = {"id": layer["id"], "type": "effect"}
                for key in EFFECT_KEYS + LAYER_KEYS:
                    if key in layer:
                        entry[key] = layer[key]
                layers.append(entry)
                continue
            # Typography at the TOP level of a layer instead of nested under
            # `card` is the single most expensive mistake this file can absorb
            # quietly. The layer stops being a card, falls through to source
            # resolution, and — with `placeholder:` as its source — becomes a
            # solid coloured box with the text dropped. Thirteen of them once
            # reached a finished-looking 2:25 render before anyone noticed.
            # There is no legitimate reading of these keys at this level, so
            # refuse rather than guess.
            misnested = (set(layer) & CARD_KEYS) - {"card"}
            if misnested and "card" not in layer:
                raise SystemExit(
                    f"{sid}/{layer.get('id')}: card typography {sorted(misnested)} is at the "
                    f"top level of the layer. It belongs under a `card` key:\n"
                    f'    {{"id": "{layer.get("id")}", "card": {{"heading": "...", ...}}, '
                    f'"rect": [...], "pop": true}}\n'
                    f"  As written, this layer is not a card and renders as a solid box."
                )
            # Card layers: live composer typography, no file to resolve.
            if "card" in layer:
                # An unrecognised card key renders as nothing at all — the
                # composer ignores what it does not know, so a mistyped
                # `sub` for `subtext` costs a whole line of on-screen copy
                # and produces no error anywhere. Name it instead.
                unknown = set(layer["card"]) - CARD_KEYS
                if unknown:
                    print(
                        f"WARNING: {sid}/{layer['id']} card has unknown key(s) "
                        f"{sorted(unknown)} — these render as NOTHING. "
                        f"Known: {sorted(CARD_KEYS)}",
                        file=sys.stderr,
                    )
                entry = {"id": layer["id"], "type": "card", **layer["card"]}
                for key in LAYER_KEYS:
                    if key in layer:
                        entry[key] = layer[key]
                layers.append(entry)
                continue
            kind, value = parse_source(layer["source"])
            entry = {"id": layer["id"]}
            resolved = None
            if kind == "file":
                resolved = Path(value)
                if not resolved.is_absolute():
                    resolved = project / value
            elif kind in ("prompt", "url", "find"):
                for ext in (".mp4", ".webm", ".png", ".jpg", ".jpeg"):
                    candidate = project / "clips" / f"{sid}-{layer['id']}{ext}"
                    if candidate.exists():
                        resolved = candidate
                        break
            if kind == "placeholder" or (resolved is None and placeholders):
                entry.update({
                    "type": "placeholder",
                    "label": value if kind == "placeholder" else layer["id"].upper(),
                    "color": PLACEHOLDER_COLORS[(si + li) % len(PLACEHOLDER_COLORS)],
                })
                if kind != "placeholder":
                    # A stand-in for footage that was expected and is missing —
                    # worth naming in the summary.
                    placeholdered.append(
                        f"{sid}/{layer['id']} ({kind}: {value[:60]}) "
                        f"— expected {project / 'clips'}/{sid}-{layer['id']}.<ext>"
                    )
                elif not placeholders:
                    # An explicit `placeholder:` source is a deliberate choice
                    # while previewing a layout, and nonsense in a final build:
                    # it renders a solid coloured box in the finished video.
                    # This used to be excluded from the count unconditionally,
                    # so a build could report readyToRender=true while emitting
                    # boxes. preflight caught it, but only if you ran preflight
                    # — and the summary said the build was ready, which is
                    # exactly the sentence that persuades you not to bother.
                    placeholdered.append(
                        f"{sid}/{layer['id']} (explicit placeholder: {value[:40]}) "
                        f"— deliberate in a preview, a solid box in a real render"
                    )
            elif resolved is None:
                unresolved.append(f"{sid}/{layer['id']} ({kind}: {value[:60]})")
                continue
            else:
                if not resolved.exists():
                    raise FileNotFoundError(f"{sid}/{layer['id']}: {resolved} does not exist")
                dest = public / "clips" / f"{sid}-{layer['id']}{resolved.suffix}"
                if not dest.exists() or dest.stat().st_mtime < resolved.stat().st_mtime:
                    shutil.copy2(resolved, dest)
                is_image = resolved.suffix.lower() in IMAGE_EXTS
                entry.update({
                    "type": "image" if is_image else "video",
                    "src": f"{slug}/clips/{dest.name}",
                })
                if not is_image:
                    # The composer loops a clip that is shorter than its scene
                    # (generated footage caps at 6s while narration-driven
                    # scenes often run longer). <Loop> needs the source length
                    # in frames — OffthreadVideo has no `loop` prop.
                    entry["loop"] = True
                    entry["srcDurationInFrames"] = max(1, round(media_seconds(dest) * fps))
            for key in LAYER_KEYS:
                if key in layer:
                    entry[key] = layer[key]
            layers.append(entry)

        cum_seconds += seconds
        end_frame = round(cum_seconds * fps)
        frames = max(1, end_frame - prev_frame)
        prev_frame = end_frame
        scenes.append({
            "id": sid,
            "durationInFrames": frames,
            **({"audio": audio_rel} if audio_rel else {}),
            **({"captions": captions} if captions else {}),
            **({"overlays": scene["overlays"]} if scene.get("overlays") else {}),
            **({"captionStyle": scene["captionStyle"]} if scene.get("captionStyle") else {}),
            "layers": layers,
        })

    if unresolved and not placeholders:
        raise SystemExit(
            "Unresolved sources (generate/fetch them, or preview with --placeholders):\n  "
            + "\n  ".join(unresolved)
        )

    props = {
        "width": int(sb.get("width", 1080)),
        "height": int(sb.get("height", 1920)),
        "fps": fps,
        "scenes": scenes,
    }
    if sb.get("captionStyle"):
        props["captionStyle"] = sb["captionStyle"]
    if sb.get("music"):
        # Resolve relative to --project, not the cwd. Resolving against cwd meant
        # the score was silently dropped whenever build_props ran from anywhere
        # other than inside the project — a missing music track and no warning.
        music = Path(sb["music"])
        if not music.is_absolute():
            music = project / music
        if music.exists():
            dest = public / "audio" / music.name
            shutil.copy2(music, dest)
            props["music"] = {"src": f"{slug}/audio/{music.name}"}
        else:
            print(f"warning: music {music} not found — exporting without a score",
                  file=sys.stderr)

    props_dir = composer / "props"
    props_dir.mkdir(parents=True, exist_ok=True)
    (props_dir / f"{slug}.json").write_text(json.dumps(props, indent=2) + "\n")
    write_registry(composer)

    # Ground truth for the quality check, which wants a plan.json describing
    # what SHOULD be on screen when. Written with the measured durations the
    # render actually used, so the checker compares against reality rather
    # than the storyboard's estimate.
    plan = {
        "title": sb.get("title", ""),
        "totalDuration": round(sum(s["durationInFrames"] for s in scenes) / fps, 3),
        "scenes": [
            {
                "id": scene["id"],
                "duration": round(built["durationInFrames"] / fps, 3),
                "narration": scene.get("narration", ""),
                "visual": next(
                    (l["source"].split(":", 1)[1].strip()
                     for l in scene["layers"] if ":" in l.get("source", "")),
                    " / ".join(
                        l["card"].get("heading", "") for l in scene["layers"] if "card" in l
                    ) or "card",
                ),
                **({"voice": scene["voice"]} if scene.get("voice") else {}),
            }
            for scene, built in zip(sb["scenes"], scenes)
        ],
    }
    (project / "plan.json").write_text(json.dumps(plan, indent=2) + "\n")

    total = sum(s["durationInFrames"] for s in scenes) / fps
    return {
        "scenes": len(scenes),
        "totalSeconds": round(total, 2),
        "unresolved": len(unresolved),
        "placeholdered": len(placeholdered),
        # Spelled out so the caller cannot mistake a preview build for a
        # finished one. Empty list when nothing was stood in for.
        "placeholderDetail": placeholdered,
        "readyToRender": not placeholdered and not unresolved,
    }


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--storyboard", required=True)
    ap.add_argument("--project", required=True)
    ap.add_argument("--composer", default=str(studio_root() / "composer"))
    ap.add_argument("--placeholders", action="store_true")
    args = ap.parse_args()
    summary = build(Path(args.storyboard), Path(args.project), Path(args.composer), args.placeholders)
    # Loud on stderr, because the JSON summary alone was read as success for
    # three consecutive renders that were entirely solid colored boxes.
    if summary["placeholdered"]:
        print(
            f"WARNING: {summary['placeholdered']} layer(s) are PLACEHOLDERS, not footage. "
            "This build is a layout preview — do NOT ship it. Missing:\n  "
            + "\n  ".join(summary["placeholderDetail"]),
            file=sys.stderr,
        )
    print(json.dumps(summary))


if __name__ == "__main__":
    main()
